table financials
	lineageTag: 8e4dbb10-5b00-4ca6-a02d-a4e358875cf6

	measure 'Sales PY' = CALCULATE(SUM(financials[Sales]), SAMEPERIODLASTYEAR(financials[Date]))
		lineageTag: 96a93953-c9fe-41ed-8c30-11f534f6e876

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales YoY' = CALCULATE((SUM(financials[Sales])-[Sales PY])/[Sales PY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2a4bffd0-e1b7-4cf3-ab8d-663e1b5cac6c

	measure 'Profit PY' = CALCULATE(SUM(financials[Profit]), SAMEPERIODLASTYEAR(financials[Date]))
		lineageTag: 66b0163a-7381-4f29-9a93-f2c24a396253

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Profit YoY' = CALCULATE((SUM(financials[Profit])-[Profit PY])/[Profit PY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c35502e8-dc02-436c-bc02-6dd9b2d4f33e

	measure 'Units Sold PY' = CALCULATE(SUM(financials[Units Sold]), SAMEPERIODLASTYEAR(financials[Date]))
		lineageTag: 2988022a-b70e-49a1-bba2-44bbdef78b0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Units Sold YoY' = CALCULATE((SUM(financials[Units Sold])-[Units Sold PY])/[Units Sold PY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5ac81036-7982-4156-b47c-2e5f0e4bea80

	measure 'Discounts PY' = CALCULATE(SUM(financials[Discounts]), SAMEPERIODLASTYEAR(financials[Date]))
		lineageTag: f8c3704c-487b-4e89-8d6a-34f6b3966c21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Discounts YoY' = CALCULATE((SUM(financials[Discounts])-[Discounts PY])/[Discounts PY])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bc5753ae-c319-4c28-a4a5-e88f8fdbe334

	column Segment
		dataType: string
		lineageTag: 07a35293-3617-45a7-9ec9-871bc528b4ff
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 534f8322-9ed9-4549-934b-c20745d2efaa
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 2c941b87-9896-4a0d-b61b-4623a1ca7e14
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: f951973a-820c-41eb-b605-3ab4b4893089
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: fd8f48ac-a694-4e20-8a08-516a44a82817
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: a32bb699-e32f-4fc6-bd27-3e4469a68fd1
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 476ebdf3-cf43-4446-8b21-02a03071e0d4
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: d232ccc8-0b84-4ce6-8dc0-8f615dfbf500
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 20136704-99c9-48d2-9016-560f07d3923c
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: b5b1fcaa-4edc-4541-ac74-3e28a9fb3d07
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: f946074d-a28a-405b-816f-53092382f448
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: bb4c1e5e-3158-4db1-90eb-43ab260a57da
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6778c749-1412-44d7-be77-1123cd565557
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: bdeecef3-61bb-4c36-a31b-1a5c792e4f6c
			defaultHierarchy: LocalDateTable_88d948ee-5758-41b6-919d-2acd2fea3fbb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 4cd76d93-3820-4df0-a3f2-4875fd500b54
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 7add77fd-160d-4bdf-adf0-6d5c9d0eb655
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 709c5843-5c3c-4519-b39b-19e6c89a2f7a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.141.1754.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

